<?php include '../Campus360/includes/navitems/navitems.php'; ?>
<?php include '../Campus360/includes/navitems/loginmodal.php'; ?>
<?php include '../Campus360/includes/navitems/registermodal.php'; ?>
<?php include '../Campus360/includes/navitems/logoutmodal.php'; ?>
<?php include '../Campus360/includes/navitems/profilemodal.php'; ?>
<?php include '../Campus360/includes/navitems/updateprofilemodal.php'; ?>
<?php include '../Campus360/includes/navitems/deleteprofilemodal.php'; ?>
<?php include '../Campus360/includes/navitems/passtodltmodal.php'; ?>
<?php include '../Campus360/includes/navitems/resend_email_modal.php'; ?>
<?php include '../Campus360/includes/navitems/reset_pass_modal.php'; ?>